"""created profile and profile picture tables

Revision ID: dc5cccca9b8a
Revises: ffdc0a98111c
Create Date: 2021-03-04 15:46:30.079803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5cccca9b8a'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pic_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('nin_gt', sa.String(length=50), nullable=True),
    sa.Column('ps_gt', sa.String(length=50), nullable=True),
    sa.Column('xbox_gt', sa.String(length=50), nullable=True),
    sa.Column('steam_gt', sa.String(length=50), nullable=True),
    sa.Column('discord_gt', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('profile_pics')
    # ### end Alembic commands ###
